# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
x=np.empty((3,3,3,))
x

array([[[4.67296746e-307, 1.69121096e-306, 4.22786442e-307],
        [3.11517980e-307, 8.06609645e-308, 7.56587584e-307],
        [1.37961302e-306, 1.05699242e-307, 8.01097889e-307]],

       [[1.78020169e-306, 7.56601165e-307, 1.02359984e-306],
        [1.33510679e-306, 2.22522597e-306, 1.33511018e-306],
        [6.23057689e-307, 1.33511290e-306, 1.78019082e-306]],

       [[8.45559303e-307, 8.06612616e-308, 6.89810244e-307],
        [1.22387550e-307, 2.22522596e-306, 8.34423917e-308],
        [1.11261162e-306, 1.78021527e-306, 2.10081501e-312]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
a=np.array([[0,0,0,0,0],[1,0,0,0,0],[1,2,0,0,0],[1,2,3,0,0],[1,2,3,4,0]])
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np 
  
c = np.zeros((8, 8), dtype = int) 
  
# fill with 1 the alternate rows and columns 
c[1::2, ::2] = 1
c[::2, 1::2] = 1
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
nor=np.random.random((5,5))
print("Before Normalization")
print("\n")
print(nor)
normax,normin=nor.max(),nor.min()
nor=(nor-normin)/(normax-normin)
print("After Normalization")
print("\n")
print(nor)

Before Normalization


[[0.87117812 0.72346681 0.55871528 0.35630799 0.42790481]
 [0.98227354 0.82214319 0.32300896 0.97534014 0.73399534]
 [0.52717187 0.93394391 0.21472183 0.67951314 0.34151093]
 [0.23710845 0.4477511  0.13636903 0.28330745 0.6255829 ]
 [0.42616461 0.45180735 0.09549042 0.90145008 0.54127518]]
After Normalization


[[0.87472087 0.70815104 0.52236545 0.29411653 0.37485422]
 [1.         0.81942558 0.25656615 0.99218141 0.72002377]
 [0.48679484 0.94550006 0.13445386 0.65858574 0.2774303 ]
 [0.15969861 0.39723431 0.04609764 0.2117959  0.59777015]
 [0.37289184 0.40180842 0.         0.9088577  0.50269874]]


# 5.  How to find common values between two arrays?

In [10]:
a1=np.array([2,4,6,8,9,10])
print("\n"+"Array1="+"\n")
print(a1)
a2=np.array([3,6,9,12,15,18])
print("\n"+"Array2="+"\n")
print(a2)
com=np.intersect1d(a1,a2)
print("\n"+"Common Values are"+"\n")
print(com)


Array1=

[ 2  4  6  8  9 10]

Array2=

[ 3  6  9 12 15 18]

Common Values are

[6 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [57]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [5]:
a1=np.empty((2,2))
b1=np.empty((2,2))
print(a1)
print(b1)
# for i in a1:
#     for j in b1:
#         if i==j:
#             print("They are equal")
if a1.all()==b1.all():
    print("They are equal")

[[2.04721870e-306 2.22518658e-306]
 [1.29061142e-306 2.22523004e-307]]
[[9.34611148e-307 1.78019082e-306]
 [2.78146285e-307 1.89144859e-307]]
They are equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [12]:
x1=np.random.random(10)
print(x1)
x1.sort()
print(x1)
x1[9]=0
print(x1)

[0.48058062 0.79360626 0.50200294 0.10996936 0.77261735 0.02290523
 0.02875524 0.59360542 0.48703637 0.93560573]
[0.02290523 0.02875524 0.10996936 0.48058062 0.48703637 0.50200294
 0.59360542 0.77261735 0.79360626 0.93560573]
[0.02290523 0.02875524 0.10996936 0.48058062 0.48703637 0.50200294
 0.59360542 0.77261735 0.79360626 0.        ]


# 9. How to print all the values of an array?

In [15]:
val=np.array([[2,1,3],[4,2,5],[7,89,23]])
print(val)

[[ 2  1  3]
 [ 4  2  5]
 [ 7 89 23]]


# 10.Subtract the mean of each row of a matrix

In [21]:
sm=np.random.rand(5,5)
print("\n"+"Creating 5x5 matrix with random nos."+"\n")
print(sm)
ms=sm-sm.mean(axis=1)
print("\n"+"Subtract the mean of each row of a matrix"+"\n")
print(ms)



Creating 5x5 matrix with random nos.

[[0.63218867 0.44597295 0.84397646 0.98286598 0.72508718]
 [0.74729502 0.36687821 0.38794153 0.95552274 0.61168234]
 [0.54962641 0.76033372 0.86101655 0.14245425 0.53177851]
 [0.62191317 0.76775904 0.51560155 0.60318863 0.30998267]
 [0.162156   0.0311382  0.62095727 0.61100448 0.72403395]]

Subtract the mean of each row of a matrix

[[-0.09382958 -0.16789102  0.27493457  0.41917696  0.2952292 ]
 [ 0.02127677 -0.24698576 -0.18110036  0.39183372  0.18182436]
 [-0.17639184  0.14646975  0.29197466 -0.42123476  0.10192053]
 [-0.10410508  0.15389507 -0.05344034  0.03949962 -0.11987531]
 [-0.56386224 -0.58272576  0.05191538  0.04731547  0.29417597]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [45]:
vec1=np.ones(9)
vec2=np.random.randint(0,len(vec1),9)
print(vec2)
vec1 += np.bincount(vec2, minlength=len(vec1))
print(vec1)

[4 8 6 1 0 7 7 7 3]
[2. 2. 1. 2. 2. 1. 2. 4. 2.]


# 12.How to get the diagonal of a dot product?

In [48]:
x=np.array([[2,4],[3,6]])
y=np.array([[1,2],[5,7]])
z=np.dot(x,y)
print(z)
print("\n"+"Diagonal Values are="+"\n",np.diagonal(z))

[[22 32]
 [33 48]]

Diagonal Values are=
 [22 48]


# 13.How to find the most frequent value in an array?

In [52]:
xy=np.array([2,3,4,5,4,3,2,3,5,3,2,3,43,23,2,3,2])
xy
print(np.bincount(xy).argmax()) #bin count provides the number of times a value is repeated.
#np.argmax() returns the index of the (first) maximum value in an array.

3


# 14.How to get the n largest values of an array

In [54]:
x = np.arange(20)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19]


# 15.How to create a record array from a regular array?

In [56]:
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])
print(result)

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]
